import argparse
from pathlib import Path
import numpy as np
from tabulate import tabulate

# Default constants (you should define these somewhere or handle them dynamically)
seticore_dir = ...
signal_dir = ...

def process_file(
    f: Path,
    signal_dir : Path = None,
):
    if signal_dir is None:
        signal_dir = f.parent.parent / f"signals-{f.parent.name}"
    signals_f  = signal_dir   / (f.name + ".npy")
    signals = np.load(signals_f).T  # cols are [mean_freq, dr, snr, width]
    headers = ["Mean Frequency [GHz]", "Drift Rate [Hz/s]", "SNR", "Width [Hz]"]
    return tabulate(signals, headers=headers, floatfmt=".7g")


def main():
    parser = argparse.ArgumentParser(description="Get info regarding a file generated by osea")
    parser.add_argument("file", type=Path, help="Path to the .h5 file")
    parser.add_argument("--signal-dir", type=Path, default=None,
                        help="Directory containing .npy signal files")

    args = parser.parse_args()
    print(process_file(
        f=args.file,
        signal_dir=args.signal_dir,
    ))
    return 0


if __name__ == "__main__":
    main()
